# Generated by Django 2.0.5 on 2018-05-30 17:34

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_featured', models.BooleanField()),
                ('cover_image', models.FileField(upload_to='')),
                ('member_name', models.TextField()),
                ('member_title', models.TextField()),
                ('attribute', models.TextField()),
                ('region', models.TextField()),
                ('category', models.TextField()),
                ('creation_date', models.DateField()),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('free_links', jsonfield.fields.JSONField(verbose_name='free_links')),
            ],
        ),
    ]
