# Generated by Django 2.0.5 on 2018-06-03 06:28

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='free_links',
            field=jsonfield.fields.JSONField(blank=True, default={'key': 'value'}, null=True, verbose_name='free_links'),
        ),
    ]
