# Generated by Django 2.0.5 on 2018-05-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180530_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_image',
            field=models.FileField(default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='brand',
            name='small_introduction',
            field=models.TextField(default=''),
        ),
    ]
