# Generated by Django 2.0.5 on 2018-05-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180530_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='small_introduction',
            field=models.CharField(default='', max_length=50),
        ),
    ]
