# Generated by Django 2.0.5 on 2018-05-30 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180530_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.FileField(default='default.png', upload_to=''),
        ),
    ]
