# Generated by Django 2.0.5 on 2018-05-30 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_brand_intorduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='intorduction',
            new_name='introduction',
        ),
    ]
