# Generated by Django 2.0.5 on 2018-05-31 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20180530_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='company_address',
            field=models.CharField(default='company_address', max_length=200),
        ),
        migrations.AddField(
            model_name='brand',
            name='company_founding_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='brand',
            name='company_name',
            field=models.CharField(default='company_name', max_length=200),
        ),
        migrations.AddField(
            model_name='brand',
            name='company_representative',
            field=models.CharField(default='company_representative', max_length=200),
        ),
        migrations.AddField(
            model_name='brand',
            name='company_sales_offices',
            field=models.TextField(default='sames_offices'),
        ),
        migrations.AddField(
            model_name='brand',
            name='company_website',
            field=models.CharField(default='company_website', max_length=200),
        ),
        migrations.AddField(
            model_name='brand',
            name='cover_image',
            field=models.FileField(default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='brand',
            name='facebook_url',
            field=models.CharField(default='https://facebook.com', max_length=200),
        ),
        migrations.AddField(
            model_name='brand',
            name='instagram_url',
            field=models.CharField(default='https://instagram.com', max_length=200),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_slug',
            field=models.CharField(default='name_slug', max_length=50),
        ),
        migrations.AddField(
            model_name='brand',
            name='twitter_url',
            field=models.CharField(default='https://twitter.com', max_length=200),
        ),
    ]
