# Generated by Django 2.0.5 on 2018-05-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20180531_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='facebook_url',
            field=models.CharField(blank=True, default='https://facebook.com', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='instagram_url',
            field=models.CharField(blank=True, default='https://instagram.com', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='twitter_url',
            field=models.CharField(blank=True, default='https://twitter.com', max_length=200, null=True),
        ),
    ]
