# Generated by Django 2.0.5 on 2018-05-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20180531_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='company_introduction',
            field=models.TextField(default='company_introduction'),
        ),
    ]
