# Generated by Django 2.0.5 on 2018-05-31 04:57

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_brand_free_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='free_links',
            field=jsonfield.fields.JSONField(default={'key': 'value'}, verbose_name='free_links'),
        ),
    ]
