# Generated by Django 2.0.5 on 2018-06-01 11:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20180531_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='attribute',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='brands.Brand'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='free_links',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='free_links'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='member_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='member_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
