# Generated by Django 2.0.5 on 2018-05-31 06:21

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_slug', models.CharField(default='name_slug', max_length=50)),
                ('introduction', models.TextField(default='')),
                ('small_introduction', models.CharField(default='', max_length=50)),
                ('logo_image', models.FileField(default='default.png', upload_to='')),
                ('cover_image', models.FileField(default='default.png', upload_to='')),
                ('facebook_url', models.CharField(blank=True, default='https://facebook.com', max_length=200, null=True)),
                ('twitter_url', models.CharField(blank=True, default='https://twitter.com', max_length=200, null=True)),
                ('instagram_url', models.CharField(blank=True, default='https://instagram.com', max_length=200, null=True)),
                ('company_name', models.CharField(default='company_name', max_length=200)),
                ('company_representative', models.CharField(default='company_representative', max_length=200)),
                ('company_address', models.CharField(default='company_address', max_length=200)),
                ('company_website', models.CharField(default='company_website', max_length=200)),
                ('company_founding_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('company_sales_offices', models.TextField(default='sames_offices')),
                ('company_introduction', models.TextField(default='company_introduction')),
                ('free_links', jsonfield.fields.JSONField(default={'key': 'value'}, verbose_name='free_links')),
                ('creation_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
