# Generated by Django 2.0.5 on 2018-06-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_auto_20180603_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name_slug',
            field=models.CharField(blank=True, default='name_slug', max_length=50, null=True),
        ),
    ]
