# Generated by Django 2.0.5 on 2018-06-01 11:36

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brand_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='company_address',
            field=models.CharField(blank=True, default='company_address', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company_introduction',
            field=models.TextField(blank=True, default='company_introduction', null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company_name',
            field=models.CharField(blank=True, default='company_name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company_representative',
            field=models.CharField(blank=True, default='company_representative', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company_sales_offices',
            field=models.TextField(blank=True, default='sames_offices', null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company_website',
            field=models.CharField(blank=True, default='company_website', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='cover_image',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='brand',
            name='free_links',
            field=jsonfield.fields.JSONField(blank=True, default={'key': 'value'}, null=True, verbose_name='free_links'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='introduction',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo_image',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='brand',
            name='small_introduction',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
