# Generated by Django 2.0.5 on 2018-06-06 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_auto_20180604_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='company_address',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company_founding_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Company Founding Date'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company_introduction',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company_representative',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company_sales_offices',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company_website',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='facebook_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='instagram_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name_slug',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='small_introduction',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='twitter_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
