# Generated by Django 2.0.5 on 2018-06-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0009_auto_20180606_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name_slug',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
    ]
