# Generated by Django 2.0.5 on 2018-06-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_auto_20180606_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
